
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CompteServiceService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/restbanko/CompteService?wsdl")
public class CompteServiceService
    extends Service
{

    private final static URL COMPTESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException COMPTESERVICESERVICE_EXCEPTION;
    private final static QName COMPTESERVICESERVICE_QNAME = new QName("http://service/", "CompteServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/restbanko/CompteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPTESERVICESERVICE_WSDL_LOCATION = url;
        COMPTESERVICESERVICE_EXCEPTION = e;
    }

    public CompteServiceService() {
        super(__getWsdlLocation(), COMPTESERVICESERVICE_QNAME);
    }

    public CompteServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPTESERVICESERVICE_QNAME, features);
    }

    public CompteServiceService(URL wsdlLocation) {
        super(wsdlLocation, COMPTESERVICESERVICE_QNAME);
    }

    public CompteServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPTESERVICESERVICE_QNAME, features);
    }

    public CompteServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CompteServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CompteService
     */
    @WebEndpoint(name = "CompteServicePort")
    public CompteService getCompteServicePort() {
        return super.getPort(new QName("http://service/", "CompteServicePort"), CompteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CompteService
     */
    @WebEndpoint(name = "CompteServicePort")
    public CompteService getCompteServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "CompteServicePort"), CompteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPTESERVICESERVICE_EXCEPTION!= null) {
            throw COMPTESERVICESERVICE_EXCEPTION;
        }
        return COMPTESERVICESERVICE_WSDL_LOCATION;
    }

}
